### PR TITLE
Fix execute/2 spec

### PR DESCRIPTION
**Pull request by michallepicki**

### CODE REVIEW

**Comment by michallepicki** [comment]
Hey @whitfin , anything I can do to help get this merged? Some backround information is on ElixirForum: https://elixirforum.com/t/dialyzer-cachex-unable-to-solve-types/35750

**Comment by michallepicki** [comment]
BUMP anything? is this being maintained?

**Comment by michallepicki** [comment]
thanks!

**Comment by ryanwinchester** [comment]
@whitfin Will there be a version bump with this?

**Pull request merged**
